# This is a config for E2B sandbox template.
# You can use template ID (ei565shqf708ywy92o8k) or template name (vibe-nextjs-test234355) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("vibe-nextjs-test234355") # Sync sandbox
# sandbox = await AsyncSandbox.create("vibe-nextjs-test234355") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('vibe-nextjs-test234355')

team_id = "03e09bf4-ec78-4397-b162-6d6faf907108"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "vibe-nextjs-test234355"
template_id = "ei565shqf708ywy92o8k"
